baseURL: http://example.org/
languageCode: en-us
title: The Heirs of Britain

markup: ## needed for html in your markdown
  goldmark:
    renderer:
      unsafe: true

params:
  description: "Lorem ipsum dolor sit amet."
  socials:
    - icon: "fas fa-rss"
      url: "#"

menus:
  main:
    - name: Home
      url: "/"
      weight: 1
    - name: Sessions
      url: "/sessions"
      weight: 2
      identifier: sessions ## used for active links in navbar. it MUST match anything after the "/".

build:
  writeStats: true

permalinks:
  sessions: "/:year/:month/:day/:slug"
#-------------------------------------
## DO NOT MESS WITH THIS! USED FOR SEARCH AND RSS.
outputs:
  home:
    - html
    - rss
    - json
  page:
    - html

outputFormats:
  RSS:
    baseName: feed
    mediatype: "application/rss+xml"
