baseURL: http://example.org/
languageCode: en-us
title: The Heirs of Britain

markup: ## needed for html in your markdown
  goldmark:
    renderer:
      unsafe: true

params:
  tagline: "The chronicles of the Heirs of Britain." ## site tagline, goes under the image in the sidebar.
  sidebar:
    img: "/img/Excalibur.png" ## path to image.
    alt: "The sword Excalibur held aloft in the heir." ## Alt text for image
  meta: ## metadata in the head of the document. each option in here corresponds to the meta tag (eg the description matches to the meta decription tag in the head, etc.)
    description: "The chronicles of the Heirs of Britain. It's a campaign blog."
    author: "Trent B."
  socials:
    - icon: "fas fa-rss"
      url: "/sessions/feed.xml"

menus:
  main:
    - name: Home
      url: "/"
      weight: 1
    - name: Sessions
      url: "/sessions"
      weight: 2
      identifier: sessions ## used for active links in navbar. it MUST match anything after the "/".

build:
  writeStats: true

permalinks:
  sessions: "/:year/:month/:day/:slug"
#-------------------------------------
## DO NOT MESS WITH THIS! USED FOR SEARCH AND RSS.
outputs:
  home:
    - html
    - rss
    - json
  page:
    - html

outputFormats:
  RSS:
    baseName: feed
    mediatype: "application/rss+xml"
